name: Java CI

on:
  push:
    branches: [ "task-3-inheritance-(05.03.25)" ]
  pull_request:
    branches: [ "task-3-inheritance-(05.03.25)" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile Java Code
        run: |
          mkdir -p out
          javac -d out $(find . -name "*.java")

      - name: Run Tests
        id: run_tests
        run: |
          java -cp out main
        continue-on-error: true

      - name: Calculate Grade
        id: grade
        if: always()
        env:
          TESTS_STATUS: ${{ steps.run_tests.outcome }}
        run: |
          chmod +x .github/workflows/grade.sh
          .github/workflows/grade.sh
