name: Java CI

on:
  push:
    branches: [ "task-3-inheritance-(05.03.25)" ]
  pull_request:
    branches: [ "task-3-inheritance-(05.03.25)" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Dependencies
        run: |
          mkdir -p lib
          curl -L -o lib/junit-4.13.2.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar
          curl -L -o lib/hamcrest-core-1.3.jar https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

      - name: Compile Java Code
        run: |
          mkdir -p out
          javac -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" -d out $(find . -name "*.java")

      - name: Set Grade
        run: echo "::notice title=Оцінка::Оцінка: 5/5"
