name: Java CI

on:
  push:
    branches: [ "task-3-inheritance-(05.03.25)" ]
  pull_request:
    branches: [ "task-3-inheritance-(05.03.25)" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile Java Code
        run: |
          mkdir -p out
          javac -d out $(find . -name "*.java")

      - name: Run Tests
        id: run_tests
        run: |
          java -cp "out:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore test.MainTest
        continue-on-error: true

      - name: Оцінка
        if: ${{ steps.run_tests.outcome == 'success' }}
        run: echo "::notice title=Оцінка::Оцінка: 5/5"
