name: Grade Evaluation

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "task-1-(03.03.25)" ]
  pull_request:
    branches: [ "task-1-(03.03.25)" ]

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run grading task
        run: ./gradlew grade
