# This is a workflow for grade evaluation using build.gradle task in branch task-1-(03.03.25)
name: Grade Evaluation

on:
  push:
    branches: [ "task-1-(03.03.25)" ]
  pull_request:
    branches: [ "task-1-(03.03.25)" ]
  workflow_dispatch:

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run grading task
        run: ./gradlew grade
